// On-chain instruction-builder golden tests.
//
// Reinstates the byte-level coverage lost when session-on-chain.test.ts,
// session-server-on-chain.test.ts, and payment-channels-open-ix.test.ts were
// deleted in the cascade/MPP session rework: the settleAndSeal / topUp /
// distribute / reclaim builders in `server/session/on-chain.ts` and the
// client open builder in `client/PaymentChannels.ts` are pinned against
// golden account lists (pubkeys + signer/writable flags, in order) and
// golden instruction data bytes for a fixed deterministic fixture.
//
// The goldens were generated by running the CURRENT builders once (this PR
// added `openSlot` to the open instruction, so pre-PR goldens are stale) —
// from here on any drift in account ordering, roles, PDA derivation, or
// data encoding fails these tests. Structural assertions (discriminators,
// field offsets, PDA recomputation) accompany the byte diffs so a failure
// explains itself rather than just dumping hex.

import {
    AccountRole,
    address,
    createKeyPairSignerFromPrivateKeyBytes,
    getAddressEncoder,
    getBase58Encoder,
    getBase64Codec,
    getCompiledTransactionMessageDecoder,
    getProgramDerivedAddress,
    getTransactionDecoder,
    getU64Encoder,
    getUtf8Encoder,
} from '@solana/kit';
import { findAssociatedTokenPda } from '@solana-program/token';
import { describe, expect, test } from 'vitest';

import { buildOpenPaymentChannelTransaction, derivePaymentChannelOpen } from '../client/PaymentChannels.js';
import type { SessionRequest } from '../client/Session.js';
import { ASSOCIATED_TOKEN_PROGRAM, PYUSD, TOKEN_2022_PROGRAM, TOKEN_PROGRAM, USDC } from '../constants.js';
import { getOpenInstructionDataDecoder } from '../generated/payment-channels/instructions/open.js';
import {
    buildDistributeInstruction,
    buildEd25519VerifyInstruction,
    buildReclaimInstruction,
    buildSettleAndSealInstructions,
    buildTopUpInstruction,
    ED25519_PROGRAM_ADDRESS,
    encodeVoucherMessageBytes,
    INSTRUCTIONS_SYSVAR_ADDRESS,
    PAYMENT_CHANNELS_PROGRAM_ID,
    type ServerInstruction,
} from '../server/session/on-chain.js';
import type { SignedVoucher } from '../shared/session-types.js';

// ─────────────────────────────────────────────────────────────────────
// Deterministic fixture
// ─────────────────────────────────────────────────────────────────────

function makeSeed(byte: number): Uint8Array {
    const seed = new Uint8Array(32);
    seed.fill(byte);
    return seed;
}

async function loadFixedSigners() {
    return await Promise.all([
        createKeyPairSignerFromPrivateKeyBytes(makeSeed(0x01)), // payer
        createKeyPairSignerFromPrivateKeyBytes(makeSeed(0x02)), // operator / rentPayer
        createKeyPairSignerFromPrivateKeyBytes(makeSeed(0x03)), // payee
        createKeyPairSignerFromPrivateKeyBytes(makeSeed(0x04)), // authorized (session) signer
        createKeyPairSignerFromPrivateKeyBytes(makeSeed(0x05)), // merchant
    ]);
}

// Addresses produced by the fixed seeds above — pinned so any change to the
// signer-derivation path shows up as a readable address diff.
const PAYER = 'AKnL4NNf3DGWZJS6cPknBuEGnVsV4A4m5tgebLHaRSZ9';
const OPERATOR = '9hSR6S7WPtxmTojgo6GG3k4yDPecgJY292j7xrsUGWBu';
const PAYEE = 'GyGKxMyg1p9SsHfm15MkNUu1u9TN2JtTspcdmrtGUdse';
const AUTHORIZED = 'EdmxWPmx2WH6WgFfTdu9xfkYf3k1g5wD1zccTVySEEh1';
const MERCHANT = '8SFqwqnq4whPhs8icwHA2hQg3hUoN1qrCLK1SBx3WKwe';

const CHANNEL_ID = '11111111111111111111111111111111';
const USDC_MAINNET = 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v';
const SYSTEM_PROGRAM = '11111111111111111111111111111111';
const RENT_SYSVAR = 'SysvarRent111111111111111111111111111111111';
const SPLIT_RECIPIENT = 'HQyfh1JGDB47A6Az4MD9KgF9LqcL3ESCkN8AT9Y8atGD';
const CHALLENGED_BLOCKHASH = 'EkSnNWid2cvwEVnVx9aBqawnmiCNiDgp3gUdkDPTKN1N';
const CHALLENGED_SLOT = 9_042n;

// Canonical ATAs for the fixture (USDC mainnet mint, SPL Token program).
const PAYER_USDC_ATA = '3wvJdyFnGvaMWpbq93NU91SggiVRveULUXL6iX5VZDGP';
const CHANNEL_USDC_ATA = 'HJt8Tjdsc9ms9i4WCZEzhzr4oyf3ANcdzXrNdLPFqm3M';
const PAYEE_USDC_ATA = 'DNDTCnZkNk358qDFZd9unHtnrc73SsXcpVWtwJJMrR4B';
const TREASURY_USDC_ATA = '3m3xS513PgjPwnLbmGbgL4Nk62QEtwzuoXphVN3kfMNh';
const SPLIT_RECIPIENT_USDC_ATA = '4wRfiUqrW7F55zoXnzxSGhvufhHtFuripP2ivYTdq58G';
const EVENT_AUTHORITY = '75c2huVzDW1Eq4kD86by5392sjdJzuAT195XNgP2f2tX';

const hex = (data: ArrayLike<number>) => Buffer.from(data as Uint8Array).toString('hex');

/** [address, role] tuples of an instruction's account list, in order. */
function accountTuples(ix: ServerInstruction): (readonly [string, AccountRole])[] {
    return ix.accounts.map(account => [account.address as string, account.role] as const);
}

/** Minimal base58 encoder for fixed-byte signatures used in tests. */
function bs58Encode(bytes: Uint8Array): string {
    const ALPHABET = '123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';
    let zeros = 0;
    while (zeros < bytes.length && bytes[zeros] === 0) zeros++;
    const digits = [0];
    for (let i = zeros; i < bytes.length; i++) {
        let carry = bytes[i]!;
        for (let j = 0; j < digits.length; j++) {
            carry += digits[j]! << 8;
            digits[j] = carry % 58;
            carry = Math.floor(carry / 58);
        }
        while (carry > 0) {
            digits.push(carry % 58);
            carry = Math.floor(carry / 58);
        }
    }
    let out = '';
    for (let i = 0; i < zeros; i++) out += '1';
    for (let i = digits.length - 1; i >= 0; i--) out += ALPHABET[digits[i]!];
    return out;
}

// ─────────────────────────────────────────────────────────────────────
// encodeVoucherMessageBytes (feeds the settle path's Ed25519 precompile)
// ─────────────────────────────────────────────────────────────────────

describe('encodeVoucherMessageBytes', () => {
    test('produces the 50-byte magic-prefixed canonical voucher payload', () => {
        const bytes = encodeVoucherMessageBytes({
            channelId: CHANNEL_ID,
            cumulativeAmount: 0n,
            expiresAt: 0n,
        });
        expect(bytes.byteLength).toBe(50);
        expect(bytes[0]).toBe(0x56);
        expect(bytes[1]).toBe(0x01);
        expect(bytes.slice(2).every(b => b === 0)).toBe(true);
    });

    test('encodes magic, channelId, cumulative (u64 LE), expiresAt (i64 LE) in order', () => {
        const bytes = encodeVoucherMessageBytes({
            channelId: CHANNEL_ID,
            cumulativeAmount: 0x1234_5678n,
            expiresAt: 0x7fff_ffff_ffff_fff0n,
        });
        const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
        expect(bytes[0]).toBe(0x56);
        expect(bytes[1]).toBe(0x01);
        expect(view.getBigUint64(34, true)).toBe(0x1234_5678n);
        expect(view.getBigInt64(42, true)).toBe(0x7fff_ffff_ffff_fff0n);
    });
});

// ─────────────────────────────────────────────────────────────────────
// Ed25519 precompile
// ─────────────────────────────────────────────────────────────────────

describe('buildEd25519VerifyInstruction', () => {
    test('header layout matches the Rust precompile builder', () => {
        const signer = new Uint8Array(32).fill(0xaa);
        const signature = new Uint8Array(64).fill(0xbb);
        const message = new Uint8Array(48).fill(0xcc);
        const ix = buildEd25519VerifyInstruction({ message, signature, signer });

        expect(ix.programAddress).toBe(ED25519_PROGRAM_ADDRESS);
        expect(ix.accounts).toEqual([]);

        const data = new Uint8Array(ix.data);
        expect(data[0]).toBe(1); // num_signatures
        expect(data[1]).toBe(0); // padding
        // signature_offset = 48 (public_key_offset 16 + 32)
        expect(data[2]).toBe(48);
        expect(data[3]).toBe(0);
        // signature_instruction_index = 0xFFFF (current instruction)
        expect(data[4]).toBe(0xff);
        expect(data[5]).toBe(0xff);
        // public_key_offset = 16
        expect(data[6]).toBe(16);
        expect(data[7]).toBe(0);
        // public_key_instruction_index = 0xFFFF
        expect(data[8]).toBe(0xff);
        expect(data[9]).toBe(0xff);
        // message_data_offset = 112 (48 + 64)
        expect(data[10]).toBe(112);
        expect(data[11]).toBe(0);
        // message_data_size = 48
        expect(data[12]).toBe(48);
        expect(data[13]).toBe(0);
        // message_instruction_index = 0xFFFF
        expect(data[14]).toBe(0xff);
        expect(data[15]).toBe(0xff);

        expect(data.slice(16, 48)).toEqual(signer);
        expect(data.slice(48, 112)).toEqual(signature);
        expect(data.slice(112, 160)).toEqual(message);
        expect(data.byteLength).toBe(160);
    });

    test('rejects malformed signer / signature lengths', () => {
        expect(() =>
            buildEd25519VerifyInstruction({
                message: new Uint8Array(48),
                signature: new Uint8Array(64),
                signer: new Uint8Array(31),
            }),
        ).toThrow(/signer must be 32 bytes/);
        expect(() =>
            buildEd25519VerifyInstruction({
                message: new Uint8Array(48),
                signature: new Uint8Array(63),
                signer: new Uint8Array(32),
            }),
        ).toThrow(/signature must be 64 bytes/);
    });
});

// ─────────────────────────────────────────────────────────────────────
// settle_and_seal
// ─────────────────────────────────────────────────────────────────────

describe('buildSettleAndSealInstructions', () => {
    test('voucher-less variant: golden accounts and [disc=4][hasVoucher=0] data', async () => {
        const [, , , , merchant] = await loadFixedSigners();

        const out = buildSettleAndSealInstructions({
            channelId: CHANNEL_ID,
            merchantSigner: merchant,
        });
        expect(out.requiresEd25519Precompile).toBe(false);
        expect(out.instructions).toHaveLength(1);

        const ix = out.instructions[0]!;
        expect(ix.programAddress).toBe(PAYMENT_CHANNELS_PROGRAM_ID);
        // payee (merchant, readonly signer), channel (writable), instructions sysvar (readonly)
        expect(accountTuples(ix)).toEqual([
            [MERCHANT, AccountRole.READONLY_SIGNER],
            [CHANNEL_ID, AccountRole.WRITABLE],
            [INSTRUCTIONS_SYSVAR_ADDRESS, AccountRole.READONLY],
        ]);
        expect(merchant.address).toBe(MERCHANT);

        // The voucher lives in the ed25519 precompile; settle data is just
        // [disc=4][hasVoucher=0].
        expect(hex(ix.data)).toBe('0400');
    });

    test('voucher variant: golden Ed25519 precompile bytes prepended, [disc=4][hasVoucher=1]', async () => {
        const [, , , authorized, merchant] = await loadFixedSigners();
        const signatureBytes = new Uint8Array(64).fill(0xaa);
        const signed: SignedVoucher = {
            voucher: { channelId: CHANNEL_ID, cumulativeAmount: '500', expiresAt: 1_700_000_000 },
            signature: bs58Encode(signatureBytes),
            signatureType: 'ed25519',
            signer: authorized.address,
        };

        const out = buildSettleAndSealInstructions({
            channelId: CHANNEL_ID,
            merchantSigner: merchant,
            voucher: { authorizedSigner: authorized.address, signed },
        });
        expect(out.requiresEd25519Precompile).toBe(true);
        expect(out.instructions).toHaveLength(2);

        // Precompile IX at index 0 (settle_and_seal reads the voucher from
        // the instruction immediately before it via the instructions sysvar).
        const precompile = out.instructions[0]!;
        expect(precompile.programAddress).toBe(ED25519_PROGRAM_ADDRESS);
        expect(precompile.accounts).toEqual([]);
        const precompileData = new Uint8Array(precompile.data);
        // Structural breakdown first so a golden mismatch is explainable:
        // header (16) + authorized-signer pubkey (32) + signature (64) +
        // 50-byte voucher message.
        expect(precompileData.byteLength).toBe(16 + 32 + 64 + 50);
        expect(precompileData.slice(16, 48)).toEqual(getBase58Encoder().encode(authorized.address) as Uint8Array);
        expect(precompileData.slice(48, 112)).toEqual(signatureBytes);
        expect(precompileData.slice(112)).toEqual(
            encodeVoucherMessageBytes({
                channelId: CHANNEL_ID,
                cumulativeAmount: 500n,
                expiresAt: 1_700_000_000n,
            }),
        );
        // Golden bytes for the whole precompile instruction.
        expect(hex(precompileData)).toBe(
            '01003000ffff1000ffff70003200ffff' + // header
                'ca93ac1705187071d67b83c7ff0efe8108e8ec4530575d7726879333dbdabe7c' + // authorized signer
                'aa'.repeat(64) + // signature
                '5601' + // voucher magic
                '00'.repeat(32) + // channelId (system address = 32 zero bytes)
                'f401000000000000' + // cumulativeAmount 500 (u64 LE)
                '00f1536500000000', // expiresAt 1_700_000_000 (i64 LE)
        );

        const settle = out.instructions[1]!;
        expect(settle.programAddress).toBe(PAYMENT_CHANNELS_PROGRAM_ID);
        expect(accountTuples(settle)).toEqual([
            [MERCHANT, AccountRole.READONLY_SIGNER],
            [CHANNEL_ID, AccountRole.WRITABLE],
            [INSTRUCTIONS_SYSVAR_ADDRESS, AccountRole.READONLY],
        ]);
        expect(hex(settle.data)).toBe('0401');
    });
});

// ─────────────────────────────────────────────────────────────────────
// top_up
// ─────────────────────────────────────────────────────────────────────

describe('buildTopUpInstruction', () => {
    test('golden account list and [disc=3][amount u64 LE] data', async () => {
        const [payer] = await loadFixedSigners();
        const ix = await buildTopUpInstruction({
            amount: 1_234_567n,
            channelId: CHANNEL_ID,
            mint: USDC.mainnet!,
            payer,
            tokenProgram: TOKEN_PROGRAM,
        });
        expect(ix.programAddress).toBe(PAYMENT_CHANNELS_PROGRAM_ID);
        // payer (writable signer), channel (writable), payer ATA (writable),
        // channel ATA (writable), mint (readonly), token program (readonly).
        expect(accountTuples(ix)).toEqual([
            [PAYER, AccountRole.WRITABLE_SIGNER],
            [CHANNEL_ID, AccountRole.WRITABLE],
            [PAYER_USDC_ATA, AccountRole.WRITABLE],
            [CHANNEL_USDC_ATA, AccountRole.WRITABLE],
            [USDC_MAINNET, AccountRole.READONLY],
            [TOKEN_PROGRAM, AccountRole.READONLY],
        ]);

        const data = new Uint8Array(ix.data);
        expect(data.byteLength).toBe(1 + 8);
        expect(data[0]).toBe(3); // discriminator
        const view = new DataView(data.buffer, data.byteOffset, data.byteLength);
        expect(view.getBigUint64(1, true)).toBe(1_234_567n);
        expect(hex(data)).toBe('0387d6120000000000');
    });
});

// ─────────────────────────────────────────────────────────────────────
// distribute
// ─────────────────────────────────────────────────────────────────────

describe('buildDistributeInstruction', () => {
    test('golden 11-account header plus one writable recipient ATA per split', async () => {
        const [payer, operator, payee] = await loadFixedSigners();
        const ix = await buildDistributeInstruction({
            channelState: { channelId: CHANNEL_ID, payee: payee.address, payer: payer.address },
            mint: USDC.mainnet!,
            rentPayer: operator.address,
            splits: [
                { bps: 1000, recipient: SPLIT_RECIPIENT },
                { bps: 250, recipient: SPLIT_RECIPIENT },
            ],
            tokenProgram: TOKEN_PROGRAM,
        });
        expect(ix.programAddress).toBe(PAYMENT_CHANNELS_PROGRAM_ID);
        // Fixed header: channel, payer, rentPayer, channel ATA, payer ATA,
        // payee ATA, treasury ATA (all writable), then mint / token program /
        // event authority / self program (readonly). Tail: one writable
        // recipient ATA per split, in split order.
        expect(accountTuples(ix)).toEqual([
            [CHANNEL_ID, AccountRole.WRITABLE],
            [PAYER, AccountRole.WRITABLE],
            [OPERATOR, AccountRole.WRITABLE],
            [CHANNEL_USDC_ATA, AccountRole.WRITABLE],
            [PAYER_USDC_ATA, AccountRole.WRITABLE],
            [PAYEE_USDC_ATA, AccountRole.WRITABLE],
            [TREASURY_USDC_ATA, AccountRole.WRITABLE],
            [USDC_MAINNET, AccountRole.READONLY],
            [TOKEN_PROGRAM, AccountRole.READONLY],
            [EVENT_AUTHORITY, AccountRole.READONLY],
            [PAYMENT_CHANNELS_PROGRAM_ID, AccountRole.READONLY],
            [SPLIT_RECIPIENT_USDC_ATA, AccountRole.WRITABLE],
            [SPLIT_RECIPIENT_USDC_ATA, AccountRole.WRITABLE],
        ]);

        // [disc=7][recipients_count u32 LE][(pubkey32 + bps u16 LE) x 2]
        const data = new Uint8Array(ix.data);
        expect(data[0]).toBe(7);
        const view = new DataView(data.buffer, data.byteOffset, data.byteLength);
        expect(view.getUint32(1, true)).toBe(2);
        expect(view.getUint16(5 + 32, true)).toBe(1000);
        expect(view.getUint16(5 + 32 + 34, true)).toBe(250);
        expect(hex(data)).toBe(
            '0702000000' +
                'f3df6c4f444efb2d860ce6dae0b568b6dadee3c402fc33edab10836490385896' + // SPLIT_RECIPIENT
                'e803' + // 1000 bps
                'f3df6c4f444efb2d860ce6dae0b568b6dadee3c402fc33edab10836490385896' +
                'fa00', // 250 bps
        );
    });

    test('zero-split distribute keeps only the 11 fixed accounts', async () => {
        const [payer, operator, payee] = await loadFixedSigners();
        const ix = await buildDistributeInstruction({
            channelState: { channelId: CHANNEL_ID, payee: payee.address, payer: payer.address },
            mint: USDC.mainnet!,
            rentPayer: operator.address,
            splits: [],
            tokenProgram: TOKEN_PROGRAM,
        });
        expect(ix.accounts).toHaveLength(11);
        expect(hex(ix.data)).toBe('0700000000'); // [disc=7][count=0]
    });
});

// ─────────────────────────────────────────────────────────────────────
// reclaim
// ─────────────────────────────────────────────────────────────────────

describe('buildReclaimInstruction', () => {
    test('bare [disc=9] with channel + rentPayer writable', async () => {
        const [, operator] = await loadFixedSigners();
        const ix = buildReclaimInstruction({ channelId: CHANNEL_ID, rentPayer: operator.address });
        expect(ix.programAddress).toBe(PAYMENT_CHANNELS_PROGRAM_ID);
        expect(accountTuples(ix)).toEqual([
            [CHANNEL_ID, AccountRole.WRITABLE],
            [OPERATOR, AccountRole.WRITABLE],
        ]);
        expect(hex(ix.data)).toBe('09');
    });
});

// ─────────────────────────────────────────────────────────────────────
// client open builder (buildOpenPaymentChannelTransaction /
// derivePaymentChannelOpen)
// ─────────────────────────────────────────────────────────────────────

/**
 * Golden instruction data for the fixed open fixture, captured from the
 * current (post-openSlot) builder:
 *   [disc=1][salt=42 u64][deposit=1_000_000 u64][gracePeriod=900 u32]
 *   [openSlot=9_042 u64][recipients vec: len=1, pubkey32 + bps=250 u16]
 * openSlot is taken from the challenge's `recentSlot` and sits between
 * gracePeriod and recipients.
 */
const OPEN_GOLDEN_DATA_HEX =
    '01' + // discriminator
    '2a00000000000000' + // salt 42 (u64 LE)
    '40420f0000000000' + // deposit 1_000_000 (u64 LE)
    '84030000' + // gracePeriod 900 (u32 LE)
    '5223000000000000' + // openSlot 9_042 (u64 LE) — the challenged recentSlot
    '01000000' + // recipients vec length
    'f3df6c4f444efb2d860ce6dae0b568b6dadee3c402fc33edab10836490385896' + // SPLIT_RECIPIENT
    'fa00'; // 250 bps

/** Channel PDA for the fixed fixture (payer/payee/mint/authorized/salt=42/openSlot=9042). */
const OPEN_GOLDEN_CHANNEL = '9dcDepjEQ1UcwLYqpaTSFQZqxYeMq9cMsmL2541HdKjV';
/** ATA(channel PDA, USDC mainnet, SPL Token). */
const OPEN_GOLDEN_CHANNEL_ATA = 'AKc4oGBp3CCQbS9BDgaf3R5UKPHgh5o6iSrYjpxoe9SN';

function openChallengeRequest(overrides: Record<string, unknown> = {}): SessionRequest {
    return {
        amount: '100',
        currency: 'USDC',
        methodDetails: {
            channelProgram: PAYMENT_CHANNELS_PROGRAM_ID.toString(),
            // Gasless flow: the operator co-signs as fee payer and rentPayer.
            feePayer: true,
            feePayerKey: OPERATOR,
            gracePeriodSeconds: 900,
            network: 'mainnet',
            recentBlockhash: CHALLENGED_BLOCKHASH,
            recentSlot: CHALLENGED_SLOT.toString(),
            ...overrides,
        },
        recipient: PAYEE,
    } as unknown as SessionRequest;
}

async function buildFixtureOpen() {
    const [payer] = await loadFixedSigners();
    return await buildOpenPaymentChannelTransaction({
        authorizedSigner: AUTHORIZED,
        deposit: 1_000_000n,
        gracePeriod: 900,
        recipients: [{ bps: 250, recipient: SPLIT_RECIPIENT }],
        request: openChallengeRequest(),
        salt: 42n,
        signer: payer,
    });
}

interface TestCompiledMessage {
    header: {
        numReadonlyNonSignerAccounts: number;
        numReadonlySignerAccounts: number;
        numSignerAccounts: number;
    };
    instructions: readonly {
        accountIndices?: readonly number[];
        data?: Uint8Array;
        programAddressIndex: number;
    }[];
    lifetimeToken?: string;
    staticAccounts: readonly string[];
}

function decodeOpenMessage(transaction: string): TestCompiledMessage {
    const decoded = getTransactionDecoder().decode(getBase64Codec().encode(transaction));
    return getCompiledTransactionMessageDecoder().decode(decoded.messageBytes) as unknown as TestCompiledMessage;
}

describe('client open instruction builder', () => {
    test('open instruction data bytes match the golden buffer (salt/deposit/gracePeriod/openSlot/splits)', async () => {
        const open = await buildFixtureOpen();
        const message = decodeOpenMessage(open.transaction);
        expect(message.instructions).toHaveLength(1);
        const ix = message.instructions[0]!;
        expect(message.staticAccounts[ix.programAddressIndex]).toBe(PAYMENT_CHANNELS_PROGRAM_ID.toString());
        expect(hex(ix.data!)).toBe(OPEN_GOLDEN_DATA_HEX);

        // Decode the golden back into fields so a byte diff explains itself.
        const decoded = getOpenInstructionDataDecoder().decode(ix.data!);
        expect(decoded.discriminator).toBe(1);
        expect(decoded.openArgs.salt).toBe(42n);
        expect(decoded.openArgs.deposit).toBe(1_000_000n);
        expect(decoded.openArgs.gracePeriod).toBe(900);
        expect(decoded.openArgs.openSlot).toBe(CHALLENGED_SLOT);
        expect(decoded.openArgs.recipients).toEqual([{ bps: 250, recipient: SPLIT_RECIPIENT }]);

        // The returned open fields echo the encoded instruction.
        expect(open.deposit).toBe('1000000');
        expect(open.gracePeriod).toBe(900);
        expect(open.mint).toBe(USDC_MAINNET);
        expect(open.openSlot).toBe(CHALLENGED_SLOT.toString());
        expect(open.payee).toBe(PAYEE);
        expect(open.payer).toBe(PAYER);
        expect(open.salt).toBe('42');
    });

    test('open instruction account list is in canonical order with the operator as rentPayer', async () => {
        const open = await buildFixtureOpen();
        const message = decodeOpenMessage(open.transaction);
        const ix = message.instructions[0]!;

        // Slot layout enforced by verifyOpenTx: 0 payer, 1 rentPayer,
        // 2 payee, 3 mint, 4 authorizedSigner, 5 channel, 6 payer ATA,
        // 7 channel ATA, 8 token program, then system/rent/ATA-program/
        // event-authority/self-program.
        const accounts = (ix.accountIndices ?? []).map(index => message.staticAccounts[index]);
        expect(accounts).toEqual([
            PAYER,
            OPERATOR, // rentPayer = operator / fee payer
            PAYEE,
            USDC_MAINNET,
            AUTHORIZED,
            OPEN_GOLDEN_CHANNEL,
            PAYER_USDC_ATA,
            OPEN_GOLDEN_CHANNEL_ATA,
            TOKEN_PROGRAM,
            SYSTEM_PROGRAM,
            RENT_SYSVAR,
            ASSOCIATED_TOKEN_PROGRAM,
            EVENT_AUTHORITY,
            PAYMENT_CHANNELS_PROGRAM_ID.toString(),
        ]);

        // The compiled message pins the writable/signer flags: the operator
        // (fee payer) and payer are the two writable signers, the payer ATA,
        // channel PDA, and channel ATA are the writable non-signers, and the
        // remaining 9 accounts are readonly.
        expect(message.lifetimeToken).toBe(CHALLENGED_BLOCKHASH);
        expect(message.header).toEqual({
            numReadonlyNonSignerAccounts: 9,
            numReadonlySignerAccounts: 0,
            numSignerAccounts: 2,
        });
        expect(message.staticAccounts).toEqual([
            OPERATOR, // fee payer (writable signer)
            PAYER, // writable signer
            PAYER_USDC_ATA, // writable
            OPEN_GOLDEN_CHANNEL, // writable
            OPEN_GOLDEN_CHANNEL_ATA, // writable
            SYSTEM_PROGRAM,
            EVENT_AUTHORITY,
            ASSOCIATED_TOKEN_PROGRAM,
            PAYMENT_CHANNELS_PROGRAM_ID.toString(),
            AUTHORIZED,
            USDC_MAINNET,
            PAYEE,
            RENT_SYSVAR,
            TOKEN_PROGRAM,
        ]);

        // Partially signed: the payer has signed; the operator slot is left
        // for the server to co-sign before broadcast.
        const decoded = getTransactionDecoder().decode(getBase64Codec().encode(open.transaction));
        const signatures = decoded.signatures as Readonly<Record<string, Uint8Array | null>>;
        expect(Object.keys(signatures)).toEqual([OPERATOR, PAYER]);
        const payerSignature = signatures[PAYER];
        expect(payerSignature && payerSignature.some(byte => byte !== 0)).toBe(true);
        const operatorSignature = signatures[OPERATOR];
        expect(operatorSignature === null || operatorSignature.every(byte => byte === 0)).toBe(true);
    });

    test('channel PDA derives from [channel, payer, payee, mint, authorizedSigner, salt, openSlot]', async () => {
        const derived = await derivePaymentChannelOpen({
            authorizedSigner: AUTHORIZED,
            deposit: 1_000_000n,
            payer: PAYER,
            request: openChallengeRequest(),
            salt: 42n,
        });
        expect(derived.channelId).toBe(OPEN_GOLDEN_CHANNEL);
        expect(derived.openSlot).toBe(CHALLENGED_SLOT.toString());

        const [recomputed] = await getProgramDerivedAddress({
            programAddress: PAYMENT_CHANNELS_PROGRAM_ID,
            seeds: [
                getUtf8Encoder().encode('channel'),
                getAddressEncoder().encode(address(PAYER)),
                getAddressEncoder().encode(address(PAYEE)),
                getAddressEncoder().encode(address(USDC_MAINNET)),
                getAddressEncoder().encode(address(AUTHORIZED)),
                getU64Encoder().encode(42n),
                getU64Encoder().encode(CHALLENGED_SLOT),
            ],
        });
        expect(recomputed).toBe(OPEN_GOLDEN_CHANNEL);

        // The channel token account in the built transaction is the canonical
        // ATA of that PDA.
        const [channelAta] = await findAssociatedTokenPda({
            mint: address(USDC_MAINNET),
            owner: address(OPEN_GOLDEN_CHANNEL),
            tokenProgram: address(TOKEN_PROGRAM),
        });
        expect(channelAta).toBe(OPEN_GOLDEN_CHANNEL_ATA);
    });

    test('openSlot is a PDA seed: a different (rewound) openSlot yields a different channel', async () => {
        const rewound = await derivePaymentChannelOpen({
            authorizedSigner: AUTHORIZED,
            deposit: 1_000_000n,
            openSlot: CHALLENGED_SLOT - 1n,
            payer: PAYER,
            request: openChallengeRequest(),
            salt: 42n,
        });
        expect(rewound.openSlot).toBe((CHALLENGED_SLOT - 1n).toString());
        expect(rewound.channelId).not.toBe(OPEN_GOLDEN_CHANNEL);
    });

    test('a PYUSD challenge derives Token-2022 accounts by default', async () => {
        const [payer] = await loadFixedSigners();
        const open = await buildOpenPaymentChannelTransaction({
            authorizedSigner: AUTHORIZED,
            deposit: 1_000_000n,
            gracePeriod: 900,
            request: {
                ...(openChallengeRequest() as unknown as Record<string, unknown>),
                currency: 'PYUSD',
            } as unknown as SessionRequest,
            salt: 42n,
            signer: payer,
        });
        expect(open.mint).toBe(PYUSD.mainnet);

        const message = decodeOpenMessage(open.transaction);
        expect(message.staticAccounts).toContain(TOKEN_2022_PROGRAM);
        expect(message.staticAccounts).not.toContain(TOKEN_PROGRAM);

        const [payerTokenAccount] = await findAssociatedTokenPda({
            mint: address(PYUSD.mainnet!),
            owner: payer.address,
            tokenProgram: address(TOKEN_2022_PROGRAM),
        });
        expect(message.staticAccounts).toContain(payerTokenAccount);
    });
});
